# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. 
on:  
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: set tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ghcr.io/cownetwork/user-service:${{ steps.tag.outputs.tag }},ghcr.io/cownetwork/user-service:latest
